# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/subscription.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/subscription.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/subscription.proto\x12\x0csubscription\"\x1e\n\x0b\x42urnRequest\x12\x0f\n\x07pill_id\x18\x01 \x01(\t\"0\n\x0c\x42urnResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2T\n\x13SubscriptionService\x12=\n\x04\x42urn\x12\x19.subscription.BurnRequest\x1a\x1a.subscription.BurnResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.subscription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BURNREQUEST']._serialized_start=42
  _globals['_BURNREQUEST']._serialized_end=72
  _globals['_BURNRESPONSE']._serialized_start=74
  _globals['_BURNRESPONSE']._serialized_end=122
  _globals['_SUBSCRIPTIONSERVICE']._serialized_start=124
  _globals['_SUBSCRIPTIONSERVICE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
